### ISSUE TITLE
이 프로젝트가 디시인사이드 프로그래밍 갤러리에 올린거 맞나요?

### ISSUE THREAD

**Issue by wesd725** [Sylvia3259/rubiks-cube#1]
http://m.dcinside.com/board/programming/1546348

너무 잘 만드시고 어떻게 만드셨는지 궁금해서 찾아봤는데 이 프로젝트가 맞나해서 여쭤봅니다

**Comment by Sylvia3259** [comment]
넵 맞습니다 잘 찾아오셨네요 ㅎㅎ
글에 올라와 있는 건 b79b3bec196fc3ce000ace28532a81a2336f27b0 이 버전입니다

**Comment by wesd725** [comment]
오오 커밋 로그까지 감사해요! 열심히 소스코드 보겠습니다!
